Repository AchoBeta/AchoBeta-Recruitment, pull requests merged in 2024-01, with the labels that each got.

#6 feat: add global exception handler
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .gitignore
  pom.xml
  src/main/java/com/achobeta/common/SystemJsonResponse.java
  src/main/java/com/achobeta/common/constants/GlobalServiceStatusCode.java
  src/main/java/com/achobeta/domain/users/controller/UserController.java
  src/main/java/com/achobeta/domain/users/model/dao/BaseAssignIDEntity.java
  src/main/java/com/achobeta/domain/users/model/dao/BaseIncrIDEntity.java
  src/main/java/com/achobeta/domain/users/repository/UserRepository.java
  src/main/java/com/achobeta/domain/users/service/UserService.java
  src/main/java/com/achobeta/domain/users/service/impl/UserServiceImpl.java
  src/main/java/com/achobeta/exception/NotPermissionException.java
  src/main/java/com/achobeta/handler/GlobalExceptionHandler.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/logback-plus.xml
Labels: ✏️ Feature, 📒 Documentation

#8 feat: 短链系统提交，还有一点邮箱相关的代码
  pom.xml
  sql/short-link.sql
  src/main/java/com/achobeta/AchobetaRecruitmentApplication.java
  src/main/java/com/achobeta/domain/email/component/EmailSender.java
  src/main/java/com/achobeta/domain/email/component/po/Email.java
  src/main/java/com/achobeta/domain/excel/util/ExcelUtil.java
  src/main/java/com/achobeta/domain/shortlink/component/BloomFilterHelper.java
  src/main/java/com/achobeta/domain/shortlink/component/RedisBloomFilter.java
  src/main/java/com/achobeta/domain/shortlink/component/RedisCache.java
  src/main/java/com/achobeta/domain/shortlink/controller/ShortLinkController.java
  src/main/java/com/achobeta/domain/shortlink/mapper/ShortLinkMapper.java
  src/main/java/com/achobeta/domain/shortlink/po/ShortLink.java
  src/main/java/com/achobeta/domain/shortlink/service/ShortLinkService.java
  src/main/java/com/achobeta/domain/shortlink/service/impl/ShortLinkServiceImpl.java
  src/main/java/com/achobeta/domain/shortlink/util/HttpUrlValidator.java
  src/main/java/com/achobeta/domain/shortlink/util/ShortLinkUtils.java
  src/main/java/com/achobeta/domain/users/model/dao/BaseAssignIDEntity.java
  src/main/java/com/achobeta/domain/users/model/dao/BaseIncrIDEntity.java
  src/main/java/com/achobeta/exception/IllegalUrlException.java
  src/main/java/com/achobeta/exception/ParameterValidateException.java
  src/main/java/com/achobeta/exception/SendMailException.java
  src/main/java/com/achobeta/exception/ShortLinkGenerateException.java
  src/main/java/com/achobeta/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: ✏️ Feature

#13 feat: add docker-compose
  build.sh
  docker-compose.yml
  dockerfile
  pom.xml
Labels: ✏️ Feature

#10 feat: 添加了数据库建表sql文件
  sql/interview_schedule.sql
  sql/stu_attachment.sql
  sql/student.sql
Labels: ✏️ Feature

#14 feat: 邮箱验证码验证
  pom.xml
  src/main/java/com/achobeta/common/constants/GlobalServiceStatusCode.java
  src/main/java/com/achobeta/domain/email/component/EmailSender.java
  src/main/java/com/achobeta/domain/email/component/EmailValidator.java
  src/main/java/com/achobeta/domain/email/component/po/EmailMessage.java
  src/main/java/com/achobeta/domain/email/controller/EmailController.java
  src/main/java/com/achobeta/domain/email/model/vo/VerificationCodeTemplate.java
  src/main/java/com/achobeta/domain/email/repository/EmailRepository.java
  src/main/java/com/achobeta/domain/email/service/EmailService.java
  src/main/java/com/achobeta/domain/email/service/impl/EmailServiceImpl.java
  src/main/java/com/achobeta/domain/email/util/IdentifyingCodeValidator.java
  src/main/java/com/achobeta/domain/package-info.java
  src/main/java/com/achobeta/domain/shortlink/component/RedisCache.java
  src/main/java/com/achobeta/domain/shortlink/controller/ShortLinkController.java
  src/main/java/com/achobeta/domain/shortlink/mapper/ShortLinkMapper.java
  src/main/java/com/achobeta/domain/shortlink/po/ShortLink.java
  src/main/java/com/achobeta/domain/shortlink/service/ShortLinkService.java
  src/main/java/com/achobeta/domain/shortlink/service/impl/ShortLinkServiceImpl.java
  src/main/java/com/achobeta/domain/shortlink/util/HttpUrlValidator.java
  src/main/java/com/achobeta/domain/shortlink/util/ShortLinkUtils.java
  src/main/java/com/achobeta/domain/users/controller/UserController.java
  src/main/java/com/achobeta/domain/users/controller/package-info.java
  src/main/java/com/achobeta/domain/users/model/dao/package-info.java
  src/main/java/com/achobeta/domain/users/model/package-info.java
  src/main/java/com/achobeta/domain/users/repository/package-info.java
  src/main/java/com/achobeta/domain/users/service/impl/UserServiceImpl.java
  src/main/java/com/achobeta/domain/users/service/package-info.java
  src/main/java/com/achobeta/exception/GlobalServiceException.java
  src/main/java/com/achobeta/exception/IllegalUrlException.java
  src/main/java/com/achobeta/exception/NotPermissionException.java
  src/main/java/com/achobeta/exception/ParameterValidateException.java
  src/main/java/com/achobeta/exception/SendMailException.java
  src/main/java/com/achobeta/exception/ShortLinkGenerateException.java
  src/main/java/com/achobeta/handler/GlobalExceptionHandler.java
  src/main/java/com/achobeta/redis/RedisCache.java
  src/main/java/com/achobeta/redis/component/BloomFilterHelper.java
  src/main/java/com/achobeta/redis/component/FastJsonRedisSerializer.java
  src/main/java/com/achobeta/redis/component/RedisBloomFilter.java
  src/main/java/com/achobeta/redis/config/RedisConfig.java
  src/main/java/com/achobeta/util/ExcelUtil.java
  src/main/java/com/achobeta/util/ValidatorUtils.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/templates/identifying-code-model.html
Labels: ✏️ Feature

#16 feat: 添加token验证
  pom.xml
  sql/short_link.sql
  sql/student.sql
  src/main/java/com/achobeta/AchobetaRecruitmentApplication.java
  src/main/java/com/achobeta/common/base/BaseAssignIDEntity.java
  src/main/java/com/achobeta/common/base/BaseIncrIDEntity.java
  src/main/java/com/achobeta/common/constants/LoginType.java
  src/main/java/com/achobeta/common/constants/RoleKinds.java
  src/main/java/com/achobeta/config/WebMvcConfiguration.java
  src/main/java/com/achobeta/domain/email/controller/EmailController.java
  src/main/java/com/achobeta/domain/shortlink/model/dao/mapper/ShortLinkMapper.java
  src/main/java/com/achobeta/domain/shortlink/model/dao/po/ShortLink.java
  src/main/java/com/achobeta/domain/shortlink/service/ShortLinkService.java
  src/main/java/com/achobeta/domain/shortlink/service/impl/ShortLinkServiceImpl.java
  src/main/java/com/achobeta/domain/users/context/BaseContext.java
  src/main/java/com/achobeta/domain/users/jwt/propertities/JwtProperties.java
  src/main/java/com/achobeta/domain/users/jwt/util/JwtUtil.java
  src/main/java/com/achobeta/domain/users/model/dao/mapper/StudentMapper.java
  src/main/java/com/achobeta/domain/users/model/po/StudentEntity.java
  src/main/java/com/achobeta/domain/users/model/po/UserHelper.java
  src/main/java/com/achobeta/domain/users/model/vo/LoginVO.java
  src/main/java/com/achobeta/domain/users/service/StudentService.java
  src/main/java/com/achobeta/domain/users/service/impl/StudentServiceImpl.java
  src/main/java/com/achobeta/domain/users/service/login/LoginFactory.java
  src/main/java/com/achobeta/domain/users/service/login/LoginLauncher.java
  src/main/java/com/achobeta/domain/users/service/login/LoginStrategy.java
  src/main/java/com/achobeta/domain/users/service/login/strategy/MailLoginStrategy.java
  src/main/java/com/achobeta/domain/users/service/login/strategy/PasswordLoginStrategy.java
  src/main/java/com/achobeta/interpretor/UserInterpretor.java
  src/main/java/com/achobeta/redis/component/BloomFilterHelper.java
  src/main/java/com/achobeta/redis/component/RedisBloomFilter.java
  src/main/resources/application.yml
  src/main/resources/mapper/StudentMapper.xml
Labels: ✏️ Feature

#18 fix(mybatis): fix no default value when inserting
  src/main/java/com/achobeta/config/MybatisFillConfig.java
Labels: ☢️ Bug

#19 feat: io 线程池工具类
  src/main/java/com/achobeta/util/ShutdownHookThread.java
  src/main/java/com/achobeta/util/ThreadPoolUtil.java
Labels: ✏️ Feature
